### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by leonard-psu** [developmentseed/jupyterlite#6]
When duplicating the steps from "Client-side Lonboard in WebAssembly" lonboard/data-filter-extension.ipynb notebook the map does not render on a local machine.

I see this:

<img width="704" alt="LiteIssue" src="https://github.com/user-attachments/assets/3f410145-a2dc-4869-b466-3ad0886ae5d7">

I've tried two different methods:
conda install -c conda-forge jupyterlite-core
conda install -c conda-forge jupyterlite-core==0.4.0

and the same message appears. Do you have any suggestions?

below is my package list:

Name               | Version     | Source
------------------ | ----------- | -----------------------------------------------------------------------------------------------------------------
packaging          | 23.2        | pyodide
micropip           | 0.6.0       | pyodide
piplite            | 0.4.2       | http://127.0.0.1:8000/extensions/@jupyterlite/pyodide-kernel-extension/static/pypi/piplite-0.4.2-py3-none-any.whl
ipykernel          | 6.9.2       | pypi
comm               | 0.2.2       | pypi
traitlets          | 5.14.3      | pyodide
pyodide-kernel     | 0.4.2       | pypi
decorator          | 5.1.1       | pyodide
executing          | 2.0.1       | pyodide
matplotlib-inline  | 0.1.7       | pyodide
six                | 1.16.0      | pyodide
pure-eval          | 0.2.2       | pyodide
asttokens          | 2.4.1       | pyodide
stack-data         | 0.6.3       | pyodide
wcwidth            | 0.2.13      | pyodide
prompt-toolkit     | 3.0.43      | pyodide
Pygments           | 2.17.2      | pyodide
ipython            | 8.23.0      | pyodide
palettable         | 3.3.3       | pypi
arro3-compute      | 0.3.0       | https://ds-wheels.s3.amazonaws.com/arro3_compute-0.3.0-cp312-cp312-emscripten_3_1_58_wasm32.whl
arro3-core         | 0.3.0       | https://ds-wheels.s3.amazonaws.com/arro3_core-0.3.0-cp312-cp312-emscripten_3_1_58_wasm32.whl
jupyterlab_widgets | 3.0.13      | pypi
widgetsnbextension | 4.0.13      | pypi
ipywidgets         | 8.1.5       | pypi
psygnal            | 0.11.1      | pypi
anywidget          | 0.9.13      | pypi
lonboard           | 0.10.0b2    | pypi
geoarrow-rust-core | 0.3.0b1     | https://ds-wheels.s3.amazonaws.com/geoarrow_rust_core-0.3.0b1-cp38-abi3-emscripten_3_1_58_wasm32.whl
arro3-io           | 0.3.0       | https://ds-wheels.s3.amazonaws.com/arro3_io-0.3.0-cp312-cp312-emscripten_3_1_58_wasm32.whl
cycler             | 0.12.1      | pyodide
matplotlib-pyodide | 0.2.2       | pyodide
kiwisolver         | 1.4.5       | pyodide
typing_extensions  | 4.11.0      | pyodide
pyparsing          | 3.1.2       | pyodide
certifi            | 2024.2.2    | pyodide
pytz               | 2024.1      | pyodide
python-dateutil    | 2.9.0.post0 | pyodide
pillow             | 10.2.0      | pyodide
fonttools          | 4.51.0      | pyodide
numpy              | 1.26.4      | pyodide
pyproj             | 3.6.1       | pyodide
matplotlib         | 3.5.2       | pyodide
regex              | 2024.4.16   | pyodide
openssl            | 1.1.1n      | pyodide
ssl                | 1.0.0       | pyodide
sqlite3            | 1.0.0       | pyodide

**Comment by kylebarron** [comment]
You should check the browser console, but it's likely that you haven't installed anywidget onto the jupyterlite instance. See https://github.com/developmentseed/jupyterlite/blob/807057ef7e67f9323666d8dbef4a218b1eda4a51/requirements.txt#L1-L2

**Comment by leonard-psu** [comment]
Thank you, anywidget fixed this issue.
